version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    versioning-strategy: increase
    labels:
      - 'pr: dependencies'
    groups:
      dev-deps:
        dependency-type: 'development'
        exclude-patterns: ['prettier']
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
    cooldown:
      default-days: 7
