name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/lint.yml@94de5d411af0abade18762a5ae243601d4bbfa98 # main
    permissions:
      contents: read
