name: Release PR

on:
  workflow_dispatch:
    inputs:
      new-version:
        description: New version to release
        required: true
        type: choice
        options: [patch, minor, major]

jobs:
  release-pr:
    uses: stylelint/.github/.github/workflows/call-release-pr.yml@45666ef076bb454406bde671ade1f0f852eb70cc # 0.2.0
    with:
      new-version: ${{ github.event.inputs.new-version }}
    permissions:
      contents: write
      pull-requests: write
