name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: stylelint/.github/.github/workflows/call-release.yml@45666ef076bb454406bde671ade1f0f852eb70cc # 0.2.0
    permissions:
      contents: write
      id-token: write
